# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from noco_db_python_sdk import NocoDb

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        nocodb = NocoDb(
        
                        xc_auth = 'YOUR_API_KEY',
        
                        xc_shared_base_id = 'YOUR_API_KEY',
        
                        xc_shared_erd_id = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(nocodb)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
