# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import noco_db_python_sdk
from noco_db_python_sdk.paths.api_v2_meta_form_columns_form_view_column_id import patch
from noco_db_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiV2MetaFormColumnsFormViewColumnId(ApiTestMixin, unittest.TestCase):
    """
    ApiV2MetaFormColumnsFormViewColumnId unit test stubs
        Update Form Column
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
