# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from noco_db_python_sdk.paths.api_v2_meta_hooks_hook_id_filters.post import CreateNewFilter
from noco_db_python_sdk.paths.api_v2_meta_hooks_hook_id_filters.get import GetHookFilter
from noco_db_python_sdk.apis.tags.db_table_webhook_filter_api_raw import DBTableWebhookFilterApiRaw


class DBTableWebhookFilterApi(
    CreateNewFilter,
    GetHookFilter,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DBTableWebhookFilterApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DBTableWebhookFilterApiRaw(api_client)
