# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from noco_db_python_sdk.paths.api_v2_meta_views_view_id_columns.post import CreateNewColumn
from noco_db_python_sdk.paths.api_v2_meta_views_view_id_columns.get import ListByView
from noco_db_python_sdk.paths.api_v2_meta_views_view_id_columns_column_id.patch import UpdateColumn
from noco_db_python_sdk.apis.tags.db_view_column_api_raw import DBViewColumnApiRaw


class DBViewColumnApi(
    CreateNewColumn,
    ListByView,
    UpdateColumn,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DBViewColumnApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DBViewColumnApiRaw(api_client)
