# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from noco_db_python_sdk.paths.api_v2_meta_plugins_plugin_id.get import GetDataByIdRaw
from noco_db_python_sdk.paths.api_v2_meta_plugins_plugin_title_status.get import GetStatusRaw
from noco_db_python_sdk.paths.api_v2_meta_plugins.get import ListAllPluginsRaw
from noco_db_python_sdk.paths.api_v2_meta_plugins_test.post import TestConfigurationPostRaw
from noco_db_python_sdk.paths.api_v2_meta_plugins_plugin_id.patch import UpdateByIdRaw
from noco_db_python_sdk.paths.api_v2_meta_plugins_webhook.get import WebhookListPluginsRaw


class PluginApiRaw(
    GetDataByIdRaw,
    GetStatusRaw,
    ListAllPluginsRaw,
    TestConfigurationPostRaw,
    UpdateByIdRaw,
    WebhookListPluginsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
