# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from noco_db_python_sdk.paths.api_v2_public_calendar_view_shared_view_uuid_count_by_date.get import CalendarViewCountByDateRaw
from noco_db_python_sdk.paths.api_v2_public_calendar_view_shared_view_uuid.get import CalendarViewListSharedRowsRaw
from noco_db_python_sdk.paths.api_v2_public_shared_view_shared_view_uuid_rows.post import CreateSharedViewRowRaw
from noco_db_python_sdk.paths.api_v2_public_shared_view_shared_view_uuid_rows_row_id_relation_type_column_name.get import ListNestedDataRaw
from noco_db_python_sdk.paths.api_v2_public_shared_view_shared_view_uuid_rows.get import ListSharedRowsRaw
from noco_db_python_sdk.paths.api_v2_public_shared_view_shared_view_uuid_groupby.get import ListSharedViewRowsGroupByRaw
from noco_db_python_sdk.paths.api_v2_public_shared_view_shared_view_uuid_nested_column_name.get import NestedDataRelationListRaw
from noco_db_python_sdk.paths.api_v2_public_shared_view_shared_view_uuid_rows_export_type.get import RowsExportTypeRaw
from noco_db_python_sdk.paths.api_v2_public_shared_base_shared_base_uuid_meta.get import SharedBaseMetaGetRaw
from noco_db_python_sdk.paths.api_v2_public_shared_erd_shared_erd_uuid_meta.get import SharedErdMetaGetRaw
from noco_db_python_sdk.paths.api_v2_public_shared_view_shared_view_uuid_group_column_id.get import SharedViewGroupDataListRaw
from noco_db_python_sdk.paths.api_v2_public_shared_view_shared_view_uuid_meta.get import ViewMetaGetRaw


class PublicApiRaw(
    CalendarViewCountByDateRaw,
    CalendarViewListSharedRowsRaw,
    CreateSharedViewRowRaw,
    ListNestedDataRaw,
    ListSharedRowsRaw,
    ListSharedViewRowsGroupByRaw,
    NestedDataRelationListRaw,
    RowsExportTypeRaw,
    SharedBaseMetaGetRaw,
    SharedErdMetaGetRaw,
    SharedViewGroupDataListRaw,
    ViewMetaGetRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
