# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.notification_update import NotificationUpdate
from noco_db_python_sdk import configuration


class TestNotificationUpdate(unittest.TestCase):
    """NotificationUpdate unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
