# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.table_records_list_linked_records_response import TableRecordsListLinkedRecordsResponse
from noco_db_python_sdk import configuration


class TestTableRecordsListLinkedRecordsResponse(unittest.TestCase):
    """TableRecordsListLinkedRecordsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
