# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.db_table_column_bulk_create_update_request_ops import DbTableColumnBulkCreateUpdateRequestOps
from noco_db_python_sdk import configuration


class TestDbTableColumnBulkCreateUpdateRequestOps(unittest.TestCase):
    """DbTableColumnBulkCreateUpdateRequestOps unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
