# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.license_req import LicenseReq
from noco_db_python_sdk import configuration


class TestLicenseReq(unittest.TestCase):
    """LicenseReq unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
