# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.auth_list_base_users400_response import AuthListBaseUsers400Response
from noco_db_python_sdk import configuration


class TestAuthListBaseUsers400Response(unittest.TestCase):
    """AuthListBaseUsers400Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
