# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.db_view_update_gallery_view_data_response import DbViewUpdateGalleryViewDataResponse
from noco_db_python_sdk import configuration


class TestDbViewUpdateGalleryViewDataResponse(unittest.TestCase):
    """DbViewUpdateGalleryViewDataResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
