# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.table_records_read_by_id_response_linksbelongs_to import TableRecordsReadByIdResponseLinksbelongsTo
from noco_db_python_sdk import configuration


class TestTableRecordsReadByIdResponseLinksbelongsTo(unittest.TestCase):
    """TableRecordsReadByIdResponseLinksbelongsTo unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
