# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.db_table_sort_delete_by_id_response import DbTableSortDeleteByIdResponse
from noco_db_python_sdk import configuration


class TestDbTableSortDeleteByIdResponse(unittest.TestCase):
    """DbTableSortDeleteByIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
