# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.form_update_req import FormUpdateReq
from noco_db_python_sdk import configuration


class TestFormUpdateReq(unittest.TestCase):
    """FormUpdateReq unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
