# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.db_table_sort_update_view_sort_request import DbTableSortUpdateViewSortRequest
from noco_db_python_sdk import configuration


class TestDbTableSortUpdateViewSortRequest(unittest.TestCase):
    """DbTableSortUpdateViewSortRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
