# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.utils_clear_noco_cache_response import UtilsClearNocoCacheResponse
from noco_db_python_sdk import configuration


class TestUtilsClearNocoCacheResponse(unittest.TestCase):
    """UtilsClearNocoCacheResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
