# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.base_get_shared_base_response import BaseGetSharedBaseResponse
from noco_db_python_sdk import configuration


class TestBaseGetSharedBaseResponse(unittest.TestCase):
    """BaseGetSharedBaseResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
