# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.db_table_webhook_test_hook_create_response import DbTableWebhookTestHookCreateResponse
from noco_db_python_sdk import configuration


class TestDbTableWebhookTestHookCreateResponse(unittest.TestCase):
    """DbTableWebhookTestHookCreateResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
