# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.public_view_meta_get200_response import PublicViewMetaGet200Response
from noco_db_python_sdk import configuration


class TestPublicViewMetaGet200Response(unittest.TestCase):
    """PublicViewMetaGet200Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
