# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.base_update_base_meta_response import BaseUpdateBaseMetaResponse
from noco_db_python_sdk import configuration


class TestBaseUpdateBaseMetaResponse(unittest.TestCase):
    """BaseUpdateBaseMetaResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
