# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.string_or_null_or_boolean_or_number import StringOrNullOrBooleanOrNumber
from noco_db_python_sdk import configuration


class TestStringOrNullOrBooleanOrNumber(unittest.TestCase):
    """StringOrNullOrBooleanOrNumber unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
