# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.base_duplicate_base_post_request import BaseDuplicateBasePostRequest
from noco_db_python_sdk import configuration


class TestBaseDuplicateBasePostRequest(unittest.TestCase):
    """BaseDuplicateBasePostRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
