# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.db_table_sort_update_sort_by_id_response import DbTableSortUpdateSortByIdResponse
from noco_db_python_sdk import configuration


class TestDbTableSortUpdateSortByIdResponse(unittest.TestCase):
    """DbTableSortUpdateSortByIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
