# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.table_records_create_new_record_response import TableRecordsCreateNewRecordResponse
from noco_db_python_sdk import configuration


class TestTableRecordsCreateNewRecordResponse(unittest.TestCase):
    """TableRecordsCreateNewRecordResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
