# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.public_shared_view_group_data_list_response_item_value_list import PublicSharedViewGroupDataListResponseItemValueList
from noco_db_python_sdk import configuration


class TestPublicSharedViewGroupDataListResponseItemValueList(unittest.TestCase):
    """PublicSharedViewGroupDataListResponseItemValueList unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
