# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.db_table_duplicate_table_post_response import DbTableDuplicateTablePostResponse
from noco_db_python_sdk import configuration


class TestDbTableDuplicateTablePostResponse(unittest.TestCase):
    """DbTableDuplicateTablePostResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
