# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest

import noco_db_python_sdk
from noco_db_python_sdk.model.public_shared_base_meta_get_response import PublicSharedBaseMetaGetResponse
from noco_db_python_sdk import configuration


class TestPublicSharedBaseMetaGetResponse(unittest.TestCase):
    """PublicSharedBaseMetaGetResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
