# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAuditRowUpdateReq(TypedDict):
    pass

class OptionalAuditRowUpdateReq(TypedDict, total=False):
    # Column Name
    column_name: str

    # Foreign Key to Model
    fk_model_id: str

    # Row ID
    row_id: str

    # The previous value before the action
    prev_value: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    # The current value after the action
    value: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

class AuditRowUpdateReq(RequiredAuditRowUpdateReq, OptionalAuditRowUpdateReq):
    pass
