# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAuthResendInviteUserResponse(TypedDict):
    pass

class OptionalAuthResendInviteUserResponse(TypedDict, total=False):
    # Success Message
    msg: str

class AuthResendInviteUserResponse(RequiredAuthResendInviteUserResponse, OptionalAuthResendInviteUserResponse):
    pass
