# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.meta import Meta
from noco_db_python_sdk.type.model_bool import ModelBool
from noco_db_python_sdk.type.source import Source

class RequiredBase(TypedDict):
    pass

class OptionalBase(TypedDict, total=False):
    # Base Title
    title: str

    # Base Description
    description: str

    # List of source models
    sources: typing.List[Source]

    # Primary Theme Color
    color: str

    deleted: ModelBool

    # Unique Base ID
    id: str

    is_meta: ModelBool

    meta: Meta

    # The order in base list
    order: typing.Union[int, float]

    # Base prefix. Used in XCDB only.
    prefix: str

    type: str

    # List of linked Database Projects that this base has access to (only used in Dashboard bases so far)
    linked_db_projects: 'typing.List["Base"]'

    status: str

class Base(RequiredBase, OptionalBase):
    pass
