# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBaseCreateUiAclResponse(TypedDict):
    pass

class OptionalBaseCreateUiAclResponse(TypedDict, total=False):
    msg: str

class BaseCreateUiAclResponse(RequiredBaseCreateUiAclResponse, OptionalBaseCreateUiAclResponse):
    pass
