# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBaseReq(TypedDict):
    pass

class OptionalBaseReq(TypedDict, total=False):
    # Source Name - Default BASE will be null by default
    alias: str

    # Source Configuration
    config: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    # Inflection for columns
    inflection_column: str

    # Inflection for tables
    inflection_table: str

    # Is the data source connected externally
    is_meta: bool

    # Is the data source minimal db
    is_local: bool

    # DB Type
    type: str

class BaseReq(RequiredBaseReq, OptionalBaseReq):
    pass
