# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.audit import Audit
from noco_db_python_sdk.type.paginated import Paginated

RequiredBaseListAuditsInBaseResponse = TypedDict("RequiredBaseListAuditsInBaseResponse", {
    "list": typing.List[Audit],

    "pageInfo": Paginated,
    })

OptionalBaseListAuditsInBaseResponse = TypedDict("OptionalBaseListAuditsInBaseResponse", {
    }, total=False)

class BaseListAuditsInBaseResponse(RequiredBaseListAuditsInBaseResponse, OptionalBaseListAuditsInBaseResponse):
    pass
