# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.base_meta_diff_get_response_item import BaseMetaDiffGetResponseItem

BaseMetaDiffGetResponse = typing.List[BaseMetaDiffGetResponseItem]
