# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBaseDuplicateBasePostResponse(TypedDict):
    pass

class OptionalBaseDuplicateBasePostResponse(TypedDict, total=False):
    name: str

    id: str

class BaseDuplicateBasePostResponse(RequiredBaseDuplicateBasePostResponse, OptionalBaseDuplicateBasePostResponse):
    pass
