# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredColumnEventBody(TypedDict):
    # The title of the column associated with the event
    title: str

    # The ID of the base that the column belongs to
    base_id: str

    # The ID of the source that the column belongs to
    source_id: str

    # The ID of the column associated with the event
    id: str

    # The ID of the model that the column belongs to
    fk_model_id: str

class OptionalColumnEventBody(TypedDict, total=False):
    pass

class ColumnEventBody(RequiredColumnEventBody, OptionalColumnEventBody):
    pass
