# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.formula_column_req import FormulaColumnReq
from noco_db_python_sdk.type.link_to_another_column_req import LinkToAnotherColumnReq
from noco_db_python_sdk.type.lookup_column_req import LookupColumnReq
from noco_db_python_sdk.type.normal_column_request import NormalColumnRequest
from noco_db_python_sdk.type.rollup_column_req import RollupColumnReq

class RequiredColumnReq(TypedDict):
    pass

class OptionalColumnReq(TypedDict, total=False):
    title: str

    ai: typing.Union[int, float]

    au: typing.Union[int, float]

    source_id: str

    cc: str

    cdf: typing.Optional[str]

    clen: str

    column_name: str

    cop: str

    created_at: str

    csn: str

    ct: str

    deleted: typing.Optional[str]

    dt: str

    dtx: str

    dtxp: str

    dtxs: typing.Optional[str]

    fk_model_id: str

    id: str

    meta: typing.Optional[str]

    np: typing.Optional[str]

    ns: typing.Optional[str]

    order: typing.Union[int, float]

    pk: typing.Union[int, float]

    base_id: str

    pv: typing.Union[int, float]

    rqd: typing.Union[int, float]

    system: typing.Union[int, float]

    uidt: str

    un: typing.Union[int, float]

    unique: typing.Union[int, float]

    updated_at: str

    validate: typing.Optional[str]

    virtual: typing.Optional[str]

class ColumnReq(RequiredColumnReq, OptionalColumnReq):
    pass
ColumnReq = typing.Union[typing.Union[FormulaColumnReq, LinkToAnotherColumnReq, LookupColumnReq, NormalColumnRequest, RollupColumnReq],typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
