# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.db_table_column_bulk_create_update_request_ops import DbTableColumnBulkCreateUpdateRequestOps

class RequiredDbTableColumnBulkCreateUpdateRequest(TypedDict):
    pass

class OptionalDbTableColumnBulkCreateUpdateRequest(TypedDict, total=False):
    # Columns hash
    hash: str

    ops: DbTableColumnBulkCreateUpdateRequestOps

class DbTableColumnBulkCreateUpdateRequest(RequiredDbTableColumnBulkCreateUpdateRequest, OptionalDbTableColumnBulkCreateUpdateRequest):
    pass
