# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.meta import Meta

class RequiredDbTableUpdateMetaRequest(TypedDict):
    pass

class OptionalDbTableUpdateMetaRequest(TypedDict, total=False):
    # Table title
    title: str

    # Table name
    table_name: str

    # Base ID
    base_id: str

    meta: Meta

class DbTableUpdateMetaRequest(RequiredDbTableUpdateMetaRequest, OptionalDbTableUpdateMetaRequest):
    pass
