# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.id import Id
from noco_db_python_sdk.type.model_bool import ModelBool
from noco_db_python_sdk.type.string_or_null import StringOrNull

class RequiredGridColumn(TypedDict):
    pass

class OptionalGridColumn(TypedDict, total=False):
    id: Id

    fk_view_id: Id

    fk_column_id: Id

    base_id: Id

    source_id: Id

    show: ModelBool

    # Grid Column Order
    order: typing.Union[int, float]

    # Column Width
    width: str

    help: StringOrNull

    group_by: ModelBool

    # Group By Order
    group_by_order: typing.Union[int, float]

    group_by_sort: StringOrNull

class GridColumn(RequiredGridColumn, OptionalGridColumn):
    pass
