# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.id import Id
from noco_db_python_sdk.type.kanban_column import KanbanColumn
from noco_db_python_sdk.type.meta import Meta
from noco_db_python_sdk.type.string_or_null import StringOrNull

class RequiredKanban(TypedDict):
    pass

class OptionalKanban(TypedDict, total=False):
    # Kanban Title
    title: str

    id: Id

    fk_grp_col_id: StringOrNull

    fk_view_id: Id

    fk_cover_image_col_id: StringOrNull

    # Kanban Columns
    columns: typing.List[KanbanColumn]

    meta: Meta

class Kanban(RequiredKanban, OptionalKanban):
    pass
