# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.paginated import Paginated
from noco_db_python_sdk.type.plugin import Plugin

RequiredPluginWebhookListPluginsResponse = TypedDict("RequiredPluginWebhookListPluginsResponse", {
    })

OptionalPluginWebhookListPluginsResponse = TypedDict("OptionalPluginWebhookListPluginsResponse", {
    "list": typing.List[Plugin],

    "pageInfo": Paginated,
    }, total=False)

class PluginWebhookListPluginsResponse(RequiredPluginWebhookListPluginsResponse, OptionalPluginWebhookListPluginsResponse):
    pass
