# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.project_event_body import ProjectEventBody

class RequiredProjectEvent(TypedDict):
    # The ID of the user
    fk_user_id: str

    type: str

    body: ProjectEventBody

class OptionalProjectEvent(TypedDict, total=False):
    pass

class ProjectEvent(RequiredProjectEvent, OptionalProjectEvent):
    pass
