# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProjectUserReq(TypedDict):
    # Base User Email
    email: str

    # Base User Role
    roles: str

class OptionalProjectUserReq(TypedDict, total=False):
    pass

class ProjectUserReq(RequiredProjectUserReq, OptionalProjectUserReq):
    pass
