# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProjectEventBody(TypedDict):
    # The title of the base
    title: str

    # The ID of the base
    id: str

    # The type of the base
    type: str

class OptionalProjectEventBody(TypedDict, total=False):
    pass

class ProjectEventBody(RequiredProjectEventBody, OptionalProjectEventBody):
    pass
