# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.public_shared_view_group_data_list_response_item_value import PublicSharedViewGroupDataListResponseItemValue

class RequiredPublicSharedViewGroupDataListResponseItem(TypedDict):
    # The Grouped Key
    key: str

    value: PublicSharedViewGroupDataListResponseItemValue

class OptionalPublicSharedViewGroupDataListResponseItem(TypedDict, total=False):
    pass

class PublicSharedViewGroupDataListResponseItem(RequiredPublicSharedViewGroupDataListResponseItem, OptionalPublicSharedViewGroupDataListResponseItem):
    pass
