# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSharedBaseReq(TypedDict):
    pass

class OptionalSharedBaseReq(TypedDict, total=False):
    # Password to protect the base
    password: str

    # The role given the target user
    roles: str

class SharedBaseReq(RequiredSharedBaseReq, OptionalSharedBaseReq):
    pass
