# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.model_bool import ModelBool
from noco_db_python_sdk.type.string_or_null import StringOrNull

class RequiredSignUpReq(TypedDict):
    # Email address of the user
    email: str

    # Password of the user
    password: str

class OptionalSignUpReq(TypedDict, total=False):
    firstname: StringOrNull

    lastname: StringOrNull

    token: StringOrNull

    ignore_subscribe: ModelBool

class SignUpReq(RequiredSignUpReq, OptionalSignUpReq):
    pass
