# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.id import Id

class RequiredSort(TypedDict):
    pass

class OptionalSort(TypedDict, total=False):
    id: Id

    fk_column_id: Id

    fk_model_id: Id

    # Source ID
    source_id: str

    # Sort direction
    direction: str

    order: typing.Union[int, float]

    # Base ID
    base_id: str

class Sort(RequiredSort, OptionalSort):
    pass
