# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.source_update_details_request_config_connection import SourceUpdateDetailsRequestConfigConnection

class RequiredSourceUpdateDetailsRequestConfig(TypedDict):
    pass

class OptionalSourceUpdateDetailsRequestConfig(TypedDict, total=False):
    client: str

    connection: SourceUpdateDetailsRequestConfigConnection

class SourceUpdateDetailsRequestConfig(RequiredSourceUpdateDetailsRequestConfig, OptionalSourceUpdateDetailsRequestConfig):
    pass
