# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.model_bool import ModelBool
from noco_db_python_sdk.type.string_or_null import StringOrNull

class RequiredSource(TypedDict):
    pass

class OptionalSource(TypedDict, total=False):
    alias: StringOrNull

    # Source Configuration
    config: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    enabled: ModelBool

    # Unique Source ID
    id: str

    # Inflection for columns
    inflection_column: str

    # Inflection for tables
    inflection_table: str

    is_meta: ModelBool

    is_local: ModelBool

    # The order of the list of sources
    order: typing.Union[int, float]

    # The base ID that this source belongs to
    base_id: str

    # DB Type
    type: str

class Source(RequiredSource, OptionalSource):
    pass
