# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTableRecordsReadByIdResponseLinksbelongsTo(TypedDict):
    pass

class OptionalTableRecordsReadByIdResponseLinksbelongsTo(TypedDict, total=False):
    Id: typing.Union[int, float]

    Title: str

class TableRecordsReadByIdResponseLinksbelongsTo(RequiredTableRecordsReadByIdResponseLinksbelongsTo, OptionalTableRecordsReadByIdResponseLinksbelongsTo):
    pass
