# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.table_records_update_patch_table_records_response_item import TableRecordsUpdatePatchTableRecordsResponseItem

TableRecordsUpdatePatchTableRecordsResponse = typing.List[TableRecordsUpdatePatchTableRecordsResponseItem]
