# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from noco_db_python_sdk.type.form import Form
from noco_db_python_sdk.type.gallery import Gallery
from noco_db_python_sdk.type.grid import Grid
from noco_db_python_sdk.type.id import Id
from noco_db_python_sdk.type.kanban import Kanban
from noco_db_python_sdk.type.map import Map
from noco_db_python_sdk.type.meta import Meta
from noco_db_python_sdk.type.model_bool import ModelBool
from noco_db_python_sdk.type.string_or_null import StringOrNull

class RequiredView(TypedDict):
    # View Title
    title: str

    fk_model_id: Id

    show: ModelBool

    # View Type
    type: typing.Union[int, float]

class OptionalView(TypedDict, total=False):
    source_id: Id

    id: Id

    # Lock Type of the view
    lock_type: str

    meta: Meta

    # The rder of the list of views
    order: typing.Union[int, float]

    password: StringOrNull

    base_id: Id

    show_system_fields: ModelBool

    is_default: ModelBool

    uuid: StringOrNull

    # Associated View Model
    view: typing.Union[Form, Gallery, Grid, Kanban, Map]

class View(RequiredView, OptionalView):
    pass
