# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredWebhook(TypedDict):
    pass

class OptionalWebhook(TypedDict, total=False):
    title: str

    id: str

    type: str

class Webhook(RequiredWebhook, OptionalWebhook):
    pass
