# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredWelcomeEvent(TypedDict):
    # The ID of the user receiving the welcome message
    fk_user_id: str

    # The type of event, which should be set to 'WELCOME'
    type: str

    # An empty object
    body: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class OptionalWelcomeEvent(TypedDict, total=False):
    pass

class WelcomeEvent(RequiredWelcomeEvent, OptionalWelcomeEvent):
    pass
