# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class BaseUpdateSharedBaseResponse(BaseModel):
    uuid: typing.Optional[str] = Field(None, alias='uuid')

    url: typing.Optional[str] = Field(None, alias='url')

    roles: typing.Optional[str] = Field(None, alias='roles')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
