# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from noco_db_python_sdk.pydantic.hook_req import HookReq

class HookTestReq(BaseModel):
    hook: HookReq = Field(alias='hook')

    # Payload to be sent
    payload: typing.Union[bool, date, datetime, dict, float, int, list, str, None] = Field(alias='payload')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
