# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class MapColumn(BaseModel):
    # The ID of the source that this map column belongs to
    source_id: typing.Optional[str] = Field(None, alias='source_id')

    # Foreign Key to Column
    fk_column_id: typing.Optional[str] = Field(None, alias='fk_column_id')

    # Foreign Key to View
    fk_view_id: typing.Optional[str] = Field(None, alias='fk_view_id')

    # Unique ID of Map Column
    id: typing.Optional[str] = Field(None, alias='id')

    # the order in the list of map columns
    order: typing.Optional[typing.Union[int, float]] = Field(None, alias='order')

    # The ID of the base that this map column belongs to
    base_id: typing.Optional[str] = Field(None, alias='base_id')

    # Whether to show this column or not
    show: typing.Optional[typing.Union[int, float]] = Field(None, alias='show')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
