# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from noco_db_python_sdk.pydantic.source_update_details_request_config import SourceUpdateDetailsRequestConfig

class SourceUpdateDetailsRequest(BaseModel):
    alias: typing.Optional[str] = Field(None, alias='alias')

    type: typing.Optional[str] = Field(None, alias='type')

    config: typing.Optional[SourceUpdateDetailsRequestConfig] = Field(None, alias='config')

    inflection_column: typing.Optional[str] = Field(None, alias='inflection_column')

    inflection_table: typing.Optional[str] = Field(None, alias='inflection_table')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
