# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from noco_db_python_sdk.pydantic.source_update_details_request_config_connection import SourceUpdateDetailsRequestConfigConnection

class SourceUpdateDetailsRequestConfig(BaseModel):
    client: typing.Optional[str] = Field(None, alias='client')

    connection: typing.Optional[SourceUpdateDetailsRequestConfigConnection] = Field(None, alias='connection')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
