# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from noco_db_python_sdk.pydantic.table_records_delete_by_array_response_item import TableRecordsDeleteByArrayResponseItem

TableRecordsDeleteByArrayResponse = typing.List[TableRecordsDeleteByArrayResponseItem]
