# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from noco_db_python_sdk.pydantic.id import Id
from noco_db_python_sdk.pydantic.model_bool import ModelBool

class ViewColumnReq(BaseModel):
    fk_column_id: typing.Optional[Id] = Field(None, alias='fk_column_id')

    show: typing.Optional[ModelBool] = Field(None, alias='show')

    # The order of the list of views.
    order: typing.Optional[typing.Union[int, float]] = Field(None, alias='order')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
