# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import noco_db_python_sdk
from noco_db_python_sdk.paths.api_v2_meta_maps_map_view_id import get
from noco_db_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiV2MetaMapsMapViewId(ApiTestMixin, unittest.TestCase):
    """
    ApiV2MetaMapsMapViewId unit test stubs
        Get Map View
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
