# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from noco_db_python_sdk import schemas  # noqa: F401


class Form(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Model for Form
    """


    class MetaOapg:
        
        class properties:
            title = schemas.StrSchema
        
            @staticmethod
            def id() -> typing.Type['Id']:
                return Id
        
            @staticmethod
            def banner_image_url() -> typing.Type['AttachmentRes']:
                return AttachmentRes
            
            
            class columns(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['FormColumn']:
                        return FormColumn
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['FormColumn'], typing.List['FormColumn']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'columns':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'FormColumn':
                    return super().__getitem__(i)
        
            @staticmethod
            def email() -> typing.Type['StringOrNull']:
                return StringOrNull
            fk_model_id = schemas.StrSchema
            source_id = schemas.StrSchema
            heading = schemas.StrSchema
            
            
            class lock_type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "collaborative": "COLLABORATIVE",
                        "locked": "LOCKED",
                        "personal": "PERSONAL",
                    }
                
                @schemas.classproperty
                def COLLABORATIVE(cls):
                    return cls("collaborative")
                
                @schemas.classproperty
                def LOCKED(cls):
                    return cls("locked")
                
                @schemas.classproperty
                def PERSONAL(cls):
                    return cls("personal")
        
            @staticmethod
            def logo_url() -> typing.Type['AttachmentRes']:
                return AttachmentRes
        
            @staticmethod
            def meta() -> typing.Type['Meta']:
                return Meta
        
            @staticmethod
            def redirect_after_secs() -> typing.Type['StringOrNull']:
                return StringOrNull
        
            @staticmethod
            def redirect_url() -> typing.Type['TextOrNull']:
                return TextOrNull
        
            @staticmethod
            def show_blank_form() -> typing.Type['ModelBool']:
                return ModelBool
        
            @staticmethod
            def subheading() -> typing.Type['TextOrNull']:
                return TextOrNull
        
            @staticmethod
            def submit_another_form() -> typing.Type['ModelBool']:
                return ModelBool
        
            @staticmethod
            def success_msg() -> typing.Type['TextOrNull']:
                return TextOrNull
            __annotations__ = {
                "title": title,
                "id": id,
                "banner_image_url": banner_image_url,
                "columns": columns,
                "email": email,
                "fk_model_id": fk_model_id,
                "source_id": source_id,
                "heading": heading,
                "lock_type": lock_type,
                "logo_url": logo_url,
                "meta": meta,
                "redirect_after_secs": redirect_after_secs,
                "redirect_url": redirect_url,
                "show_blank_form": show_blank_form,
                "subheading": subheading,
                "submit_another_form": submit_another_form,
                "success_msg": success_msg,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> 'Id': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["banner_image_url"]) -> 'AttachmentRes': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["columns"]) -> MetaOapg.properties.columns: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> 'StringOrNull': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fk_model_id"]) -> MetaOapg.properties.fk_model_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["source_id"]) -> MetaOapg.properties.source_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["heading"]) -> MetaOapg.properties.heading: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lock_type"]) -> MetaOapg.properties.lock_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["logo_url"]) -> 'AttachmentRes': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["meta"]) -> 'Meta': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["redirect_after_secs"]) -> 'StringOrNull': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["redirect_url"]) -> 'TextOrNull': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["show_blank_form"]) -> 'ModelBool': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subheading"]) -> 'TextOrNull': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["submit_another_form"]) -> 'ModelBool': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["success_msg"]) -> 'TextOrNull': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["title", "id", "banner_image_url", "columns", "email", "fk_model_id", "source_id", "heading", "lock_type", "logo_url", "meta", "redirect_after_secs", "redirect_url", "show_blank_form", "subheading", "submit_another_form", "success_msg", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union['Id', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["banner_image_url"]) -> typing.Union['AttachmentRes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["columns"]) -> typing.Union[MetaOapg.properties.columns, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> typing.Union['StringOrNull', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fk_model_id"]) -> typing.Union[MetaOapg.properties.fk_model_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["source_id"]) -> typing.Union[MetaOapg.properties.source_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["heading"]) -> typing.Union[MetaOapg.properties.heading, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lock_type"]) -> typing.Union[MetaOapg.properties.lock_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["logo_url"]) -> typing.Union['AttachmentRes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["meta"]) -> typing.Union['Meta', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["redirect_after_secs"]) -> typing.Union['StringOrNull', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["redirect_url"]) -> typing.Union['TextOrNull', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["show_blank_form"]) -> typing.Union['ModelBool', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subheading"]) -> typing.Union['TextOrNull', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["submit_another_form"]) -> typing.Union['ModelBool', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["success_msg"]) -> typing.Union['TextOrNull', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["title", "id", "banner_image_url", "columns", "email", "fk_model_id", "source_id", "heading", "lock_type", "logo_url", "meta", "redirect_after_secs", "redirect_url", "show_blank_form", "subheading", "submit_another_form", "success_msg", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        id: typing.Union['Id', schemas.Unset] = schemas.unset,
        banner_image_url: typing.Union['AttachmentRes', schemas.Unset] = schemas.unset,
        columns: typing.Union[MetaOapg.properties.columns, list, tuple, schemas.Unset] = schemas.unset,
        email: typing.Union['StringOrNull', schemas.Unset] = schemas.unset,
        fk_model_id: typing.Union[MetaOapg.properties.fk_model_id, str, schemas.Unset] = schemas.unset,
        source_id: typing.Union[MetaOapg.properties.source_id, str, schemas.Unset] = schemas.unset,
        heading: typing.Union[MetaOapg.properties.heading, str, schemas.Unset] = schemas.unset,
        lock_type: typing.Union[MetaOapg.properties.lock_type, str, schemas.Unset] = schemas.unset,
        logo_url: typing.Union['AttachmentRes', schemas.Unset] = schemas.unset,
        meta: typing.Union['Meta', schemas.Unset] = schemas.unset,
        redirect_after_secs: typing.Union['StringOrNull', schemas.Unset] = schemas.unset,
        redirect_url: typing.Union['TextOrNull', schemas.Unset] = schemas.unset,
        show_blank_form: typing.Union['ModelBool', schemas.Unset] = schemas.unset,
        subheading: typing.Union['TextOrNull', schemas.Unset] = schemas.unset,
        submit_another_form: typing.Union['ModelBool', schemas.Unset] = schemas.unset,
        success_msg: typing.Union['TextOrNull', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Form':
        return super().__new__(
            cls,
            *args,
            title=title,
            id=id,
            banner_image_url=banner_image_url,
            columns=columns,
            email=email,
            fk_model_id=fk_model_id,
            source_id=source_id,
            heading=heading,
            lock_type=lock_type,
            logo_url=logo_url,
            meta=meta,
            redirect_after_secs=redirect_after_secs,
            redirect_url=redirect_url,
            show_blank_form=show_blank_form,
            subheading=subheading,
            submit_another_form=submit_another_form,
            success_msg=success_msg,
            _configuration=_configuration,
            **kwargs,
        )

from noco_db_python_sdk.model.attachment_res import AttachmentRes
from noco_db_python_sdk.model.form_column import FormColumn
from noco_db_python_sdk.model.id import Id
from noco_db_python_sdk.model.meta import Meta
from noco_db_python_sdk.model.model_bool import ModelBool
from noco_db_python_sdk.model.string_or_null import StringOrNull
from noco_db_python_sdk.model.text_or_null import TextOrNull
