# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from noco_db_python_sdk import schemas  # noqa: F401


class Rollup(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Model for Rollup
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def id() -> typing.Type['Id']:
                return Id
        
            @staticmethod
            def fk_column_id() -> typing.Type['Id']:
                return Id
        
            @staticmethod
            def fk_relation_column_id() -> typing.Type['Id']:
                return Id
        
            @staticmethod
            def fk_rollup_column_id() -> typing.Type['Id']:
                return Id
            
            
            class rollup_function(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def COUNT(cls):
                    return cls("count")
                
                @schemas.classproperty
                def MIN(cls):
                    return cls("min")
                
                @schemas.classproperty
                def MAX(cls):
                    return cls("max")
                
                @schemas.classproperty
                def AVG(cls):
                    return cls("avg")
                
                @schemas.classproperty
                def COUNT_DISTINCT(cls):
                    return cls("countDistinct")
                
                @schemas.classproperty
                def SUM_DISTINCT(cls):
                    return cls("sumDistinct")
                
                @schemas.classproperty
                def AVG_DISTINCT(cls):
                    return cls("avgDistinct")
            __annotations__ = {
                "id": id,
                "fk_column_id": fk_column_id,
                "fk_relation_column_id": fk_relation_column_id,
                "fk_rollup_column_id": fk_rollup_column_id,
                "rollup_function": rollup_function,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> 'Id': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fk_column_id"]) -> 'Id': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fk_relation_column_id"]) -> 'Id': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fk_rollup_column_id"]) -> 'Id': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rollup_function"]) -> MetaOapg.properties.rollup_function: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "fk_column_id", "fk_relation_column_id", "fk_rollup_column_id", "rollup_function", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union['Id', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fk_column_id"]) -> typing.Union['Id', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fk_relation_column_id"]) -> typing.Union['Id', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fk_rollup_column_id"]) -> typing.Union['Id', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rollup_function"]) -> typing.Union[MetaOapg.properties.rollup_function, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "fk_column_id", "fk_relation_column_id", "fk_rollup_column_id", "rollup_function", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union['Id', schemas.Unset] = schemas.unset,
        fk_column_id: typing.Union['Id', schemas.Unset] = schemas.unset,
        fk_relation_column_id: typing.Union['Id', schemas.Unset] = schemas.unset,
        fk_rollup_column_id: typing.Union['Id', schemas.Unset] = schemas.unset,
        rollup_function: typing.Union[MetaOapg.properties.rollup_function, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Rollup':
        return super().__new__(
            cls,
            *args,
            id=id,
            fk_column_id=fk_column_id,
            fk_relation_column_id=fk_relation_column_id,
            fk_rollup_column_id=fk_rollup_column_id,
            rollup_function=rollup_function,
            _configuration=_configuration,
            **kwargs,
        )

from noco_db_python_sdk.model.id import Id
