# coding: utf-8

"""
    NocoDB v2

    NocoDB API Documentation

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from noco_db_python_sdk import schemas  # noqa: F401


class UtilsCountCommentsResponse(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['UtilsCountCommentsResponseItem']:
            return UtilsCountCommentsResponseItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['UtilsCountCommentsResponseItem'], typing.List['UtilsCountCommentsResponseItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'UtilsCountCommentsResponse':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'UtilsCountCommentsResponseItem':
        return super().__getitem__(i)

from noco_db_python_sdk.model.utils_count_comments_response_item import UtilsCountCommentsResponseItem
