name: Build, Test, and Publish

on:
  push:
    tags:
      - "v*"  # 当推送以 "v" 开头的标签时触发，例如 v1.0.0

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine pytest flake8

      # Step 4: 检查代码质量
    #   - name: Run Lint
    #     run: |
    #       flake8 noco_db_python_sdk/
    #     continue-on-error: false  # 如果代码有问题，任务会中止

      # Step 5: 运行单元测试
    #   - name: Run Tests
    #     run: |
    #       pytest tests/ --doctest-modules --junitxml=test-results.xml
    #     continue-on-error: false  # 如果代码有问题，任务会中止

      # Step 6: 构建项目
      - name: Build package
        run: |
          python -m build

      # Step 7: 发布到 PyPI
      - name: Publish to PyPI
        if: github.ref_type == 'tag'  # 仅当触发事件是标签时执行
        env:
          TWINE_USERNAME: __token__  # 固定用户名，表示使用 API Token
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*
